site_name: pysofft
repo_url: https://github.com/TimBerberich/pysofft

docs_dir: docs/
nav:
  - Home:
      - index.md
      - speed.md
      - accuracy.md
  - Usage:
      - usage/simple.md
      - usage/multi.md
      - usage/parallelization.md
      - usage/fftw.md
      - usage/corr.md
      - usage/stats.md
  - Definitions:
      - so3_grid.md
      - array.md
      - wigner.md
  - API:
      - api/structure.md
      - Python:
          - api/python/soft.md
          - api/python/stats.md
      - Fortran:
          - pysofft/namespacemake__wigner.md
          - pysofft/namespacesoftclass.md
          - pysofft/namespaceutils.md
          - pysofft/namespacepy.md
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to system preference  
  font: false
 #   text: Roboto
 #   code: Roboto Mono
  features:
    - search.highlight
    - search.suggest
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.indexes
    - content.tabs.link
    - toc.follow
    - search.share
    - content.code.copy
    - content.code.annotations

markdown_extensions:
  - markdown.extensions.md_in_html:
  - markdown.extensions.toc:
  #- markdown_captions:
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - pymdownx.superfences:
      preserve_tabs: false
      custom_fences:
        # Mermaid diagrams
        - name: diagram
          class: diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format {kwds: {mode: generic, tag: pre}}
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
        - name: yaml
          lang: yaml
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_inline_format {kwds: {mode: generic}}
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: facelessuser
      repo: pymdown-extensions
      normalize_issue_symbols: true
  - pymdownx.tilde:
  - pymdownx.caret:
  #- pymdownx.smartsymbols:
  #- pymdownx.emoji:
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
      generic: true
      block_tag: 'pre'
  - pymdownx.mark:  
  - pymdownx.saneheaders:
  - pymdownx.blocks.details:
      types:
      - new
      - settings
      - note
      - abstract
      - info
      - tip
      - success
      - question
      - warning
      - failure
      - danger
      - bug
      - example
      - quote
  - pymdownx.blocks.html:
  - pymdownx.blocks.definition:
    
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/facelessuser
    - icon: fontawesome/brands/discord
      link: https://discord.gg/TWs8Tgr

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6



plugins:
  - mkdocstrings:
      default_handler: python
      custom_templates: docs/templates2
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: false 
            show_root_heading: true
      features:
        - search.suggest
        - search.highlight
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: False
      caption_position: bottom
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - mkdoxy:
      projects:
        pysofft:
          src-dirs: ./pysofft
          template-dir: ./docs/templates
          full-doc: true
          enable_sorting: false
          doxy-cfg:
            EXTRACT_ALL: True
            RECURSIVE: False
            OPTIMIZE_FOR_FORTRAN: True
            SOURCE_BROWSER: True
            USE_HTAGS: True
      save-api: .mkdoxy
      
extra_css:
  - style.css

hooks:
  - docs/hooks/unescape_pipe_in_pymdownx_details.py
